# Generated by Django 4.1.5 on 2023-01-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_remove_account_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
    ]
