# Generated by Django 4.1.5 on 2023-01-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book',
            field=models.FileField(null=True, upload_to='books'),
        ),
    ]
